version: '3'

services:
  app:
    build: ./
    volumes:
      - ./:/github-issues-notificator
    environment:
      NOTIFICATOR_ENV: development
    ports:
      - 8081:8081
    logging:
      driver: local

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME = gin
      - MONGO_INITDB_ROOT_PASSWORD = s3cr3t
      - MONGO_INITDB_DATABASE = githubIssuesNotificator
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  smtp:
    image: ixdotai/smtp:latest

volumes:
  mongodb_data:
